version: "3.9"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: bow-backend-flask-app
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=local
      - DB_NAME=bow_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - qdrant
    networks:
      - flask-network

  bow-worker-2:
    container_name: bow-worker-2
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=local
      - DB_NAME=bow_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - qdrant
    networks:
      - flask-network



  redis:
    image: redis:7-alpine
    container_name: bow-redis
    ports:
      - "6379:6379"
    networks:
      - flask-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: bow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  postgres_data:
  qdrant_storage:
